#!/usr/bin/env bash

RED='\033[0;31m'
NC='\033[0m'

TIME=""
DAY=""
MONTH=""
AUDIO=""

usage () {
	echo "$0 -a audiofile -t time -d day -m month"
}

if ! args=$(getopt -o a:t:d:m: -- "$@") ; then
	usage
	exit 1
fi

eval set -- "$args"
while [ $# -gt 0 ]
do
	case "$1" in
	-a)
		AUDIO=$2
		shift
		;;
	-t)
		TIME=$2
		shift
		;;
	-d)
		DAY=$2
		shift
		;;
	-m)
		MONTH=$2
		shift
		;;
	--)
		shift
		break
		;;
	*)
		echo "Invalid option: $1"
		exit 1
		;;
	esac
	shift
done

if [ -z "$AUDIO" ] ; then
	if [ -f ./alarm.mp3 ] ; then
		AUDIO="./alarm.mp3"
	else
		echo "No audio file. Please add -a <path_to_audio_file>"
		exit 1
	fi
fi

if [ -z "$TIME" ] ; then
	read -p "Enter time: " TIME
fi
if [ -z $TIME ] ; then
	echo "no time specified."
	exit 1
fi

if [ -z $DAY ] ; then
	read -p "Enter day: " DAY
fi
if [ -z $DAY ] ; then
	echo "no day specified"
	exit 1
fi

if [ -z "$MONTH" ] ; then
	read -p "Enter month: " MONTH
fi
if [ -z "$MONTH" ] ; then
	MONTH=$(date +%m)
	echo "Using month $MONTH (use -m for another)"
fi

#bounds
if [ "$MONTH" -gt 12 ] ; then
	echo "month is wrong"
	exit 1
fi
if [ "$DAY" -gt 31 ] ; then
	echo "day is wrong"
	exit 1
fi

# get format for rtcwake
alarmtime=$(date --date="${MONTH}/${DAY}/$(date +%Y) ${TIME}:00" +"%s")
# sanity check
if ! date --date=@$alarmtime +"%c" ; then
	echo -e "${RED}couldn't set alarm time${NC}"
	exit 1
fi

command -v cvlc >/dev/null 2>&1 || { echo -e >&2 "${RED}Please install vlc.${NC}"; exit 1; }

sudo rtcwake --mode no --time "$alarmtime"
while true ; do
	sleep 30
	if (date +"%R"| grep ${TIME}); then
		killall vlc
		amixer set 'Master' unmute
		amixer set 'Master' 100%
		sleep 1
		cvlc "${AUDIO}"
		exit 0
	fi
done
